doc_index.html
As an attempt to make it clearer what's in the manual. Follow-up from https://github.com/neovim/neovim/issues/1315#issuecomment-64457789.
=> Link to Python instructions on documentation page.

index.html
As @justinmk [mentioned](https://github.com/neovim/neovim.github.io/pull/85#issuecomment-70212415) since it is the best way to describe it.
This takes over where #85 left off as the author didn't take the suggestions.
=> Change monthly -> quasi-monthly for newsletter

doc_index.html
There's a lot of questions coming up on the same topics: Python support, `:!` problems, CTRL-H problems. Link to the Troubleshooting page, where some of these issues are addressed (~~I plan to add something for CTRL-H~~ actually, since it's in the milestone for the first release, it should go away soon and doesn't need to be documented).
=> [RFC] Documentation page: Link to user resources on wiki.

js/sponsors-override.js
=> add to sponsors overrides

js/sponsors-override.js
I was a bit surprised that I ended up on the front page of neovim.io. So I created a small page with few information about what I am working on.
=> Added a link and a front-image for my slug

_posts/2015-12-09-december-newsletter.md
This will go out with the 0.1 release
ccing @ZyX-I to review the information about shada
=> [WIP] December Newsletter

js/sponsors-override.js
=> Update my entry in sponsors-override.js

css/main.css
New hover button state (global on site):
=> Keep button text white on hover

index.html
Add an auto-updating post field.
Very open to suggestions for styling or different word choices.
=> Website updates

_posts/2017-05-02-newsletter.md
=> news: version 0.2

index.html
=> index.html: non-breaking spaces for better readability

js/sponsors-override.js
=> Add URL for my Bountysource slug to sponsors list

js/sponsors-override.js
=> Fix missing comma in `sponsors-override.js`

js/sponsors-override.js
Thanks for making a great tool!
=> Add my site to the sponsors list

index.html
There's outdated information about current stable version :)
=> release change

_includes/footer.html, _includes/post_sidebar.html, charter.html, doc_index.html, index.html, roadmap.html
Apply `golden-grid` to fix layout to use responsive grids.
This is to fix missing classes in template files that's causing the layout to not work as intended.
=> Fix golden grid

_posts/2020-10-28-newsletter.md
Hi - I saw your plea for help on reddit and thought I'd lend a hand ;). This is a first draft for the newsletter that would cover Neovim from v0.3.0 to v0.4.0, please let me know what you think.
@justinmk You told me on reddit you had notes about what you wanted to see in this newsletter - are they available somewhere?
=> Add newsletter #10 - Neovim v0.4.0

_posts/2020-10-28-newsletter.md
Some minor changes, sorry to do that now and not earlier...
- Fix a typo : net -> set
- Use recommendations for some words : really interesting -> fascinating
- Other consistency changes
cc @teto as you merged the newsletter.
=> Spell checking and improvements on news 10

_includes/whatisnvim.html, community.html, index.html
=> Replace riot.im links with client-independent matrix.to links

_data/nav.yml, doc/developer.html, doc/general.html, doc/lsp.html, doc/lua-resources.html, doc/treesitter.html
Very much WIP but I wanted to collect some feedback before spending more time. This explodes the current documentation of the website in several subsections: LSP/treesitter/lua etc
@neovim/website-maintainers
=> Document new aspects of neovim 0.5

index.html
Update current version to 0.5 on the homepage.
=> feat(0.5) update current version to 0.5

index.html
resolve https://github.com/neovim/neovim.github.io/issues/262
=> fix content(img) on tablet

sponsors.html
=> feat: clarify usage of donations

_includes/nav.html
resolve https://github.com/neovim/neovim.github.io/issues/265
=> Accessibility update link

_posts/2022-04-26-newsletter.md
Copy and pasted directly from https://gpanders.com/blog/whats-new-in-neovim-0-7/, we can make further modifications/touch-ups as needed.
=> news: Add 2022-04-26 newsletter

sponsors.html
Add an explicit width and height property to images on the /sponsors
page for page speed. I calculated the values by inspecting the actual
rendered size.
Also standardize indentation values and style to the majority in the
file and project (2 spaces).
=> layout: add width/height to images

index.html
This keeps the names looking uniform and also uses my preferred name which people actually know me by online. (I am Wolfy87 on reddit reluctantly, most people know me as Olical in the OSS space).
Maybe the name should even be: Oliver "Olical" Caldwell? Although that's then not uniform, I just thought this'd look better.
=> Improve name in "Impressions", @Wolfy87 -> Oliver Caldwell
