develop/style-guide.xml
Due to the declarations generator we do not need separate function declarations.
=> Remove notes about declarations and add about generator

doc_index.html
I renamed `Installing` -> `Installing-Neovim` for consistency with `Building-Neovim`, but was informed by @fwalch that this website depends on the old name, so this fixes that.
=> Fix broken link

_data/nav.yml, community.html, css/main.css
The idea is to link to this page from https://github.com/neovim/neovim#community, https://github.com/neovim/neovim/wiki/Communicating, and https://github.com/neovim/neovim/wiki/Contributing#give-support.
Speaking of https://github.com/neovim/neovim/wiki/Communicating, should the code of conduct be linked on this page as well? Is "Support" a good title, or should it be called e.g. "Community" instead?
=> Add community page.

_layouts/default.html, css/main.css, original-sponsors.html, sponsors.html
@tarruda I took a pass at some cleanup on the sponsors page.
I removed the hard coded width on the `pre` tag and let the text wrap there since it's so easy to miss 90% of the command. I also tweaked the styling on the sponsor list a bit.
Current (note the dollar sign / amount breaks at narrower widths):
Updated:
=> Sponsor page cleanup

css/main.css
Just a small tweak to fix some formatting lost in the merge conflicts of #101. Everything was fixed by using `.sponsor-image` instead of `.sponsor-logo` as introduced in #100.
Current:
Updated:
=> Sponsor table tweaks

sponsors.html
I just noticed that the merge of #101 dismissed the text of the sponsor page updated in #100, most importantly the notice that you can post to the mailing list if you want to provide your sponsor URL and don't have a GitHub account. Copied in the text from #100 and did a few other minor changes.
@tarruda You could also add a link to the sponsors page on the Bountysource Salt page.
=> [RFC] Improve text on sponsors page.

develop/style-guide.xml
Also fixes two style errors inside:
1. `.c.generated.h` in header file (should be `.h.generated.h`).
2. Missing `// NVIM_FOO_H`.
=> Make “Integration with declarations generator” section look better

js/sponsors-override.js
I'd also like to include this image as my avatar on the sponsors page (https://pbs.twimg.com/profile_images/378800000436837670/4933f9be3fd1c43573c70808a5833278.png).
=> Add pygeek website to sponsor override

Rakefile, _config.yml, _includes/nav.html, _layouts/default.html, _posts/2014-11-07-november-newsletter.md, about.html, develop/guide.xsl, index.html, js/sponsors-override.js, news.xml, sponsors.html
Use HTTPS links to avoid "some unencrypted elements on this website"
warning when accessing https://neovim.io.
Also remove usages of "site.baseurl", which doesn't exist (i.e. is an
empty string), and fix warnings in HTML-Proofer.
=> Use HTTPS links.

Rakefile, index.html
User "sehnsucht" mentioned on IRC that the existing wording about `nvim_from_vim` might a bit ambiguous.
This is my take on it; suggestions welcome!
=> Improve wording on home page.

css/main.css
My take on https://github.com/neovim/neovim.github.io/issues/122
* Remove global 'pre' font sizing to improve readability of the generated vim help documents.
* Add small sizing for `.faq dd pre` as it is primarily used for a copy-paste snippet for which readability is secondary.
=> Specify pre font size for faq sidebar only

.travis.yml, Rakefile, css/main.css, index.html
Pulled out html and css changes from PR https://github.com/neovim/neovim.github.io/pull/135 stemming from issue https://github.com/neovim/neovim.github.io/issues/134. Here's what the homepage will look like if this PR is accepted:
Since the rake tests / ruby setup has been broken for quite some time, this PR is also disabling those tests for now.
=> Install Now Button (Html only)

js/sponsors-override.js
My entry didn't have the link again. This should fix it. Neovim is awesome.
=> Fix madis-nomme entry in sponsors list

develop/style-guide.xml
Clarify project guideline on use of `const` for non-pointer parameters.
ref: https://github.com/neovim/neovim/pull/8684#issuecomment-403618769
ref: https://github.com/neovim/neovim/pull/8142#discussion_r175252438
=> code style: guideline for `const` parameters

.travis.yml
fix CI failure:
$ bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
You must use Bundler 2 or greater with this lockfile.
=> CI: update travis env

roadmap.html
This commit makes the link in the road map point to the tracking issue on github rather than an already merged pull request. This allows for easier monitoring of the current status of tree-sitter integration.
=> Point to the tree-sitter tracking issue instead of a pull request

doc_index.html
Fixes container grid on `/doc/` page.
=> layout: Fix doc index container grid. 

css/main.css
I opened the [vim diff page](https://neovim.io/doc/user/vim_diff.html#nvim-features) on half of my laptop screen and saw the words breaking in the middle.
I fixed it and now the words won't break awkwardly in the middle when the screen is narrow.
Before:
After:
=> Fix word breaking on vim_diff

sponsors.html
Fix sponsors layout so it uses the new golden grid layout.
=> Fix sponsors layout to use golden grid

_posts/2020-04-14-newsletter.md
Removed the trailing slash, which made the link produce a 404 error page.
=> 2020-04-14 Newsletter: fix blog post link

index.html
Update sponsors section on homepage to include (and prioritize github sponsors).
=> Update Sponsors info on Home Page

_data/nav.yml
may be a bit slow because of the redirection but  best to give a stable url ?
cc @mjlbach
=> feat: add link to our discourse

Gemfile, Gemfile.lock
Ruby 2 shipped webrick by default, but Ruby 3 does not. Installing it for Ruby 2
as well poses no harm.
=> deps: add webrick

doc2/README.md, doc2/general.html, doc2/lsp.html, doc2/lua-resources.html, doc2/treesitter.html
thus nullifying my intention of putting the files in a different directory so that neovim/doc can crawl that directory: I 've tested locally and canonical_url seems like what I wanted in the first place
=> fix: permalink changes the output folder

roadmap.html
closes https://github.com/neovim/neovim.github.io/issues/238
=> Update roadmap after 0.5 release

index.html
It seems Blockchain.info are now Blockchain.com.
Also corrected an inconsistent case of "GitHub".
=> Resolve BTC link redirection

_layouts/default.html
The minified versions of the bootstrap JavaScript and CSS are included
in the repository, but not referenced. In addition to saving bandwidth,
this also fixes the two 404s caused by the un-minified files trying to
call non-existent `.map` files.
=> Use minified bootstrap JS/CSS

_layouts/default.html
Reverts neovim/neovim.github.io#267
Layout is messed up:
=> revert use of minified CSS

_includes/logo.svg, _includes/nav.html
Add both `aria-label` property and the SVG `<title>` tag to mark up the
graphic for screen reader accessibility. Use both for the widest
support.
Add `role="img"` to the SVG, since SVGs do not have graphics semantics
by default, and the logo is used as a graphic (obviously), so marking it
as one gets us a lot of proper accessibility for free.
Add the exact width and height in dedicated properties instead of inline
`style`; the `width` and `height` properties are static, so the browser
can calculate the size of the image before layout rendering, increasing
performance.
Note that the Github preview looks as if the image has shrank, but that's
only because the Github SVG parser doesn't interpret `style` tags, and
wouldn't have the right value with the existing `em` sizing anyway.
Minify the …
=> Label Neovim logo for accessibility

_includes/nav.html
Add an aria label to the main hamburger menu button. Since this element
is an icon, and thus does not provide any inherent textual context,
screen readers have nothing other than "button" to read here.
=> Add aria label to hamburger menu

css/lato.css
There is a period during page load where the web font is not downloaded,
so text is invisible. If there is a network hiccup, this state could
be permanent for the session.
Modern browsers support `font-display`, which controls strategies for
how to handle this problem.
Use the `swap` property, which strikes a balance between preferring the
specified web font, but quickly falling back to a default if it does not
load in time, so text will always be visible.
Older browsers will ignore the property, maintaining the current
behavior.
See https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
=> Prevent flash of invisible text

index.html
Since 0.8.0 has been release, it should be advertised as the latest available version of Neovim.
=> Mention 0.8 as the latest version

_layouts/default.html, css/neovim-hi.css
Adds a pygment/rogue colorscheme for syntax highlighting. 
Related to #303
=> Add syntax highlighting css

index.html
Linking directly into a matrix client app is discouraged. It is recommended to use [Matrix.to instead](https://matrix.to). [Matrix.to instead](https://matrix.to) provides a client agnostic way to link to a matrix room/space/event/etc, with support for a large number of clients.
=> Use matrix.to link

css/main.css, index.html
New section is broken in mobile view. The horizontal scrollbar show up. This PR is to let twitter timeline to decide width and add margin to table in news section.
=> fix: news section layout in mobile view

css/main.css
Discussed in https://github.com/neovim/neovim.github.io/issues/310
It seems like the default bootstrap style adds a padding to the `mark` element, which makes the display of DocSearch results a bit weird (see `before`). This PR provides an override for the `mark` element, only if it's a child of the `DocSearch` class (see `after`).
| Before | After |
|--------|--------|
| <img width="1131" alt="Screenshot 2023-06-27 at 22 46 33" src="https://github.com/neovim/neovim.github.io/assets/20689156/df91d21a-f34e-412c-88b0-3e6382c7f988"> | <img width="1197" alt="Screenshot 2023-06-27 at 22 47 10" src="https://github.com/neovim/neovim.github.io/assets/20689156/eb54506b-4f90-4bbe-9046-98dab1e5e4cd"> |
=> fix(css): override default bootstrap style for DocSearch

_layouts/default.html, css/main.css
> disclaimer: take a look at https://github.com/neovim/neovim.github.io/pull/328 first as this branch is stacked on it.
This PR aims at matching the DocSearch styles to the Neovim colors, see table for preview.
| Description | Before | After |
|:--------:|--------|--------|
| Update of the search button and keys | <img width="1280" alt="Screenshot 2023-06-28 at 00 11 16" src="https://github.com/neovim/neovim.github.io/assets/20689156/ad9207fc-ef02-4a58-8991-fe199e3e060b"> | <img width="1280" alt="Screenshot 2023-06-28 at 22 45 57" src="https://github.com/neovim/neovim.github.io/assets/20689156/dfab73ea-f282-42a5-9749-c8fae5d94459"> |
| Update of the modal and result highlights | <img width="1280" alt="Screenshot 2023-06-28 at 00 12 01" …
=> feat(search): match DocSearch style with Neovim

doc2/index.html, index.html, roadmap.html
Follow-up to the Wiki cleanup on neovim/neovim.
@dundargoc
=> doc: update links to content moved out of Neovim Wiki

roadmap.html
neovim 0.10.0-dev builds include the following new parsers:
* bash, markdown, python
Tree-sitter parsers in the 0.9 branch:
* https://github.com/neovim/neovim/blob/release-0.9/cmake.deps/cmake/BuildTreesitterParsers.cmake#L37-L39
versus tree-sitter parsers in the 0.10-dev branch:
* https://github.com/neovim/neovim/blob/master/cmake.deps/cmake/BuildTreesitterParsers.cmake#L37-L40
This can also be checked by downloading the binary linux tarballs and check the list of dynamic link libraries under the parser/ subdirectory. For example:
neovim 0.10.0-dev nightly:
```
$ curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
$ tar tf nvim-linux64.tar.gz  | grep parser | sort
nvim-linux64/lib/nvim/parser/
nvim-linux64/lib/nvim/parser/bash.so …
```
=> roadmap: add bash to the list of new treesitter parsers

index.html
Add link to Github discussions and more explicitly direct new users to vi.stackexchange.com
=> Add link to Github discussions

index.html
Mention `:Tutor` on home page. This may actually be relevant for a different sections because this is also useful for people who are not coming from Vim.
=> mention nvim tutor in index.html

.well-known/atproto-did, _config.yml
This commit adds a 'https://neovim.io/.well-known/atproto-did' page with the content of a DID value taken from dedicated Neovim BlueSky account. With this page present, account will be able to use a `@neovim.io` handle which assures users that this is an "official" BlueSky account of Neovim team.
Details:
- The '.well-known' is a long established dedicated directory name for automated verification that certain domain belongs to a certain account on third-party site.
- The DID value of an account is a public information, so there should not be issues with it being present here in the open.
=> feat: enable BlueSky account verification

404.html
Adds a custom 404 page that matches the Neovim website design and provides helpful navigation for users who encounter broken links.
fix #382
Currently, non-existent URLs on neovim.io show GitHub's default 404 page, which doesn't match the site's branding and doesn't help users navigate back to relevant content.
- Created `404.html` using Jekyll's layout system with `{% include nav.html %}`
- Matches the existing Neovim website color scheme and typography
- Includes working navigation header with search functionality
- Provides helpful links to popular pages (Documentation, News, GitHub, etc.)
- Responsive design that works on mobile and desktop
- Includes auto-redirect logic for common typos (docs → doc/, etc.)
- Tracks 404 errors for analytics if available
- ✅ Uses existing Jekyll layout …
=> Add custom 404 page with Neovim branding
